### ISSUE TITLE
可以为yk L1  mt7620 弄一个ssr的ipk文件么

### ISSUE THREAD

**Issue by Viktorboy** [yichya/shadowsocks-openwrt#1]
我刷的  x wrt 固件 一个openwrt的衍生品
但是他不支持 ssr  请问 我再你这里可以获得ssr 服务支持么
我想用他的这个固件 再添加上 ssr服务
想空中卡 走免流

**Comment by yichya** [comment]
xwrt 基本上就是 openwrt master 加上一些额外的机型支持，您随便找一找其他的 ssr 包应该都可以装上。
这个仓库不是 ssr，是原版 ss，免流之类的没试过
